import { SkillContext, SkillResult } from './base';
import pptxgen from 'pptxgenjs';

export async function generatePPTSkill(context: SkillContext): Promise<SkillResult> {
    const { session, inputs } = context;

    // 1. Initialize PPT
    const pres = new pptxgen();
    pres.layout = 'LAYOUT_16x9';

    // 2. Title Slide
    const slide1 = pres.addSlide();
    slide1.background = { color: '000000' }; // Dark mode
    slide1.addText(session.title, {
        x: 1, y: 1.5, w: '80%', h: 1,
        fontSize: 44, color: 'FFFFFF', bold: true, align: 'left'
    });
    slide1.addText(`Project: ${context.session.projectId}\nGenerated by Knowledge Bookshelf`, {
        x: 1, y: 3, w: '80%', h: 1,
        fontSize: 18, color: 'AAAAAA', align: 'left'
    });

    // 3. Content Slides (from Inputs)
    // For MVP, we create one slide per input
    inputs.forEach(input => {
        const slide = pres.addSlide();
        slide.background = { color: '000000' };

        // Title
        slide.addText(input.title, {
            x: 0.5, y: 0.5, w: '90%', h: 0.5,
            fontSize: 24, color: 'FFFFFF', bold: true
        });
        // Content
        slide.addText(input.content.substring(0, 1000), { // Truncate for now
            x: 0.5, y: 1.2, w: '90%', h: 4,
            fontSize: 14, color: 'DDDDDD',
            valign: 'top', align: 'left'
        });
    });

    // 4. Generate Base64
    const b64 = await pres.write({ outputType: 'base64' });

    return {
        title: 'Session Presentation.pptx',
        content: `data:application/vnd.openxmlformats-officedocument.presentationml.presentation;base64,${b64}`,
        type: 'ppt'
    };
}
